import assert from 'node:assert/strict';
import { collectMetrics, repositories } from './collect_github_metrics.mjs';
import { assessHealth, hasUsableCache } from './pipeline_health.mjs';

const brief = {aiDiscovery:[{links:[{url:'https://github.com/owner/project.git'},{url:'https://github.com/owner/project/issues'}]},{links:[{url:'https://github.com/owner/project'}]}]};
assert.deepEqual(repositories(brief), ['owner/project']);
const now = new Date('2026-10-08T03:00:00Z');
const good = await collectMetrics(brief, {}, async()=>({ok:true,json:async()=>({stargazers_count:1234,forks_count:0})}), now);
assert.equal(good.repositories['owner/project'].forks, 0);
const failed = await collectMetrics(brief, good, async()=>({ok:false,status:403}), new Date('2026-10-09T03:00:00Z'));
assert.equal(failed.repositories['owner/project'].stars,1234);
assert.equal(failed.repositories['owner/project'].fetchedAt,now.toISOString());
assert.equal(failed.repositories['owner/project'].status,'STALE');
const missing = await collectMetrics(brief, {}, async()=>{throw new Error('offline');},now);
assert.equal(missing.repositories['owner/project'].status,'FAILED');
assert.equal(missing.repositories['owner/project'].stars,undefined);
const invalid = await collectMetrics(brief, {}, async()=>({ok:true,json:async()=>({stargazers_count:-1,forks_count:0})}),now);
assert.equal(invalid.repositories['owner/project'].status,'FAILED');
const manifest = {active:[{key:'required',required:true},{key:'optional'}]};
const cache = {date:'2026-10-08',sources:{required:{status:'OK',count:3},optional:{status:'FAILED',count:0,error:'HTTP 403'}}};
const usable={...cache,crawler:{engine:'playwright-chromium'},sources:{optional:{status:'FAILED',count:0,items:[],actionableCount:0,actionableItems:[]},required:{status:'OK',count:1,items:[{url:'https://example.com'}],actionableCount:0,actionableItems:[]}}};
assert.equal(hasUsableCache(usable,manifest,'2026-10-08'),true);
assert.equal(hasUsableCache(usable,manifest,'2026-10-09'),false);
assert.equal(hasUsableCache({...usable,crawler:{}},manifest,'2026-10-08'),false);
assert.equal(hasUsableCache({...usable,sources:{}},manifest,'2026-10-08'),false);
assert.equal(hasUsableCache({...usable,sources:{...usable.sources,optional:{status:'FAILED'}}},manifest,'2026-10-08'),false);
const expanded={...manifest,nextCandidates:[{key:'newDiscovery',status:'SHADOW',crawlerSpec:{adapter:'hackerNewsTop'}}]};
assert.equal(hasUsableCache(usable,expanded,'2026-10-08'),false,'New shadow sources must actually be crawled before scheduled cache reuse');
assert.equal(hasUsableCache({...usable,shadowSources:{newDiscovery:{status:'OK',items:[],count:0,actionableItems:[],actionableCount:0}}},expanded,'2026-10-08'),false,'Empty successful shadow results are invalid');
assert.equal(hasUsableCache({...usable,shadowSources:{newDiscovery:{status:'FAILED',items:[],count:0,actionableItems:[],actionableCount:0}}},expanded,'2026-10-08'),true,'A recorded optional shadow failure may be reused');
let health=assessHealth(cache,manifest,{date:'2026-10-07'},now);
assert.equal(health.publication.status,'STALE');
assert.equal(health.sources.status,'PARTIAL');
assert.deepEqual(health.sources.failed,['optional']);
health=assessHealth(cache,manifest,{date:'2026-10-07'},new Date('2026-10-07T23:50:00Z'));
assert.equal(health.publication.status,'PENDING');
health=assessHealth({...cache,sources:{}},manifest,{date:'2026-10-08'},now);
assert.equal(health.sources.status,'FAILED');
assert.equal(health.publication.status,'OK');
assert.equal(assessHealth({...cache,date:'2026-10-07'},manifest,{date:'2026-10-08'},now).collection.status,'STALE');
console.log('PASS: metrics success/zero/retention/errors and separate source/collection/publication health');
