import assert from 'node:assert/strict';
import { collectMetrics, repositories } from './collect_github_metrics.mjs';
import { assessHealth } from './pipeline_health.mjs';

const brief = {aiDiscovery:[{links:[{url:'https://github.com/owner/project.git'},{url:'https://github.com/owner/project/issues'}]},{links:[{url:'https://github.com/owner/project'}]}]};
assert.deepEqual(repositories(brief), ['owner/project']);
const now = new Date('2026-10-08T03:00:00Z');
const good = await collectMetrics(brief, {}, async()=>({ok:true,json:async()=>({stargazers_count:1234,forks_count:0})}), now);
assert.equal(good.repositories['owner/project'].forks, 0);
const failed = await collectMetrics(brief, good, async()=>({ok:false,status:403}), new Date('2026-10-09T03:00:00Z'));
assert.equal(failed.repositories['owner/project'].stars,1234);
assert.equal(failed.repositories['owner/project'].fetchedAt,now.toISOString());
assert.equal(failed.repositories['owner/project'].status,'STALE');
const missing = await collectMetrics(brief, {}, async()=>{throw new Error('offline');},now);
assert.equal(missing.repositories['owner/project'].status,'FAILED');
assert.equal(missing.repositories['owner/project'].stars,undefined);
const invalid = await collectMetrics(brief, {}, async()=>({ok:true,json:async()=>({stargazers_count:-1,forks_count:0})}),now);
assert.equal(invalid.repositories['owner/project'].status,'FAILED');
const manifest = {active:[{key:'required',required:true},{key:'optional'}]};
const cache = {date:'2026-10-08',sources:{required:{status:'OK',count:3},optional:{status:'FAILED',count:0,error:'HTTP 403'}}};
let health=assessHealth(cache,manifest,{date:'2026-10-07'},now);
assert.equal(health.publication.status,'STALE');
assert.equal(health.sources.status,'PARTIAL');
assert.deepEqual(health.sources.failed,['optional']);
health=assessHealth(cache,manifest,{date:'2026-10-07'},new Date('2026-10-07T23:50:00Z'));
assert.equal(health.publication.status,'PENDING');
health=assessHealth({...cache,sources:{}},manifest,{date:'2026-10-08'},now);
assert.equal(health.sources.status,'FAILED');
assert.equal(health.publication.status,'OK');
assert.equal(assessHealth({...cache,date:'2026-10-07'},manifest,{date:'2026-10-08'},now).collection.status,'STALE');
console.log('PASS: metrics success/zero/retention/errors and separate source/collection/publication health');
